NOISSUE - Configure charts to display other values
mainflux/ui pull request #117
Opened 2020-09-30 16:45 UTC by darkodraskovic

Currently, charts only display number values. Enable the display of other types of values, such as booleans, too.

2020-09-30 16:59 UTC, manuio requested changes

2020-09-30 16:59 UTC, manuio commented on src/app/shared/chart/chart.component.ts
> +  findValue(message: MsgResp): any {
I'm not sure about `find`. Maybe `parseValue` ?

2020-09-30 16:59 UTC, manuio commented on src/app/common/interfaces/mainflux.interface.ts
> +export interface MsgResp {
Maybe better `MfxMsg` or `MainfluxMsg`

2020-10-01 08:53 UTC, manuio approved these changes
LGTM

2020-10-01 09:46 UTC, drasko approved these changes
LGTM

2020-10-01 09:46 UTC, merged