NOISSUE - Rename Orgs -> Groups
mainflux/ui pull request #126
Opened 2020-10-26 21:51 UTC by manuio

2020-10-26 22:21 UTC, drasko requested changes
I think it must be `UserGroups`

2020-10-27 09:17 UTC, blokovi approved these changes

2020-10-27 09:34 UTC, mteodor approved these changes

2020-10-27 09:49 UTC, drasko approved these changes
LGTM

2020-10-27 09:49 UTC, merged