NOISSUE - Add experimental conditional build
mainflux/ui pull request #135
Opened 2020-12-01 18:21 UTC by darkodraskovic

2020-12-02 09:35 UTC, manuio requested changes

2020-12-02 09:35 UTC, manuio commented on src/app/pages/pages-menu.ts
> +  MENU_ITEMS.push(
I would simply replace all Menu. With push() this is going to change the structure

2020-12-03 22:31 UTC, manuio requested changes

2020-12-03 22:31 UTC, manuio commented on package.json
> +    "build:prod": "npm run build -- --prod",
Keep `--aot`

2020-12-03 22:31 UTC, manuio commented on package.json
> +    "experimental:prod": "npm run build --configuration=experimental-prod",
Add `--aot` here

2020-12-04 09:50 UTC, manuio requested changes

2020-12-04 09:50 UTC, manuio commented on src/app/pages/pages-menu.ts
> +
Remove this blank line

2020-12-04 10:57 UTC, manuio approved these changes
LGTM

2020-12-04 11:23 UTC, dusanb94 approved these changes

2020-12-04 11:44 UTC, merged