NOISSUE - Add defaults.ini as docker volume for grafana container
mainflux/ui pull request #205
Opened 2021-04-07 14:37 UTC by mteodor

Signed-off-by: Mirko Teodorovic <mirko.teodorovic@gmail.com>

defaults.ini is copied from docker container and mounted as volume for grafana so that we can fine tune settings for grafana

2021-04-07 15:07 UTC, drasko requested changes
If you put this file in `docker/config/`, by the name we cannot conclude that it relates to Grafana.

Rename to `grafana-defaults.ini` or put a subdir `grafana` in `config` dir.

2021-04-07 15:23 UTC, dusanb94 submitted a review, later dismissed

2021-04-07 15:39 UTC, blokovi submitted a review, later dismissed

2021-04-15 08:20 UTC, manuio approved these changes
LGTM

2021-04-15 08:20 UTC, manuio approved these changes

2021-04-15 08:21 UTC, dusanb94 approved these changes

2021-04-15 09:01 UTC, blokovi approved these changes

2021-04-15 11:14 UTC, nmarcetic approved these changes

2021-04-16 00:11 UTC, drasko approved these changes
LGTM

2021-04-16 00:11 UTC, merged